server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/,http://eureka1:8761/eureka/

spring:
  application:
    name: eureka-client

feign:
  hystrix:
    enabled: true   # feign开启hystrix必须添加的参数
