server:
  port: 8762

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka2
  client:
    register-with-eureka: false
    service-url:
      default-zone: http://eureka1:8761/eureka/
    fetch-registry: false