server:
  port: 8080

spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true